### ISSUE TITLE
Gui: Could not conect: conection Refused

### ISSUE THREAD

**Issue by lcornelius101** [JarbasAl/personal-mycroft-backend#1]
on runnning python start_gui.py it opens a window and the window says Could not conect: conection Refused

**Comment by JarbasAl** [comment]
check the newly added examples folder, the gui also requires extra packages

```
sudo apt install python3-pyqt5 python3-pyqt5.qtwebkit libqt5webkit5-dev libgirepository1.0-
pip install pywebview
pip install pygobject
```
